version: '3'

services:
  quotes-widget:
    image: quotes-widget
    pull_policy: never
    restart: always
    container_name: quotes-widget
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.quotes-widget.entrypoints=http"
      - "traefik.http.routers.quotes-widget.rule=Host(`quotes.thiagosol.com`)"
      - "traefik.http.routers.quotes-widget-secure.entrypoints=https"
      - "traefik.http.routers.quotes-widget-secure.rule=Host(`quotes.thiagosol.com`)"
      - "traefik.http.routers.quotes-widget-secure.tls=true"
      - "traefik.http.routers.quotes-widget-secure.service=quotes-widget-secure"
      - "traefik.http.services.quotes-widget-secure.loadbalancer.server.port=80"
      - "traefik.docker.network=external-sol-apis"
    networks:
      - external-sol-apis
      - logging-network
    logging:
      driver: loki
      options:
        loki-url: "http://loki:3100/loki/api/v1/push"
        loki-external-labels: "service=quotes-widget,type=service"
        loki-retries: "5"
        loki-batch-size: "400"
        mode: "non-blocking"
    deploy:
      resources:
        limits:
          memory: 50M

networks:
  logging-network:
    external: true
  external-sol-apis:
    external: true
